CryptoCoins/Models/Coin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CryptoCoins.Models
{
    public class Coin
    {
        public int CoinId { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        [NotMapped] // Do not map to database
        public bool IsChecked { get; set; }
    }
}

CryptoCoins/Models/CoinContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CryptoCoins.Models
{
    public class CoinContext : DbContext
    {
        public DbSet<Coin> CoinContexts { get; set; }

        public CoinContext(DbContextOptions<CoinContext> options) : base(options) { }
    }
}

CryptoCoins/Models/ErrorViewModel.cs
using System;

namespace CryptoCoins.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CryptoCoins/Controllers/CoinsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CryptoCoins.Models;

namespace CryptoCoins.Controllers
{
    public class CoinsController : Controller
    {
        private readonly CoinContext _context;

        public CoinsController(CoinContext context)
        {
            _context = context;
        }

        // GET: Coins
        public async Task<IActionResult> Index()
        {
            return View(await _context.CoinContexts.ToListAsync());
        }
        // Update coin quantity based on user submits
        public async Task<IActionResult> CryptoChoice(List<Coin> coins)
        {
            foreach (var item in coins)
            {
                if(item.IsChecked == true)
                {
                    Coin coin = await _context.CoinContexts.FirstAsync(x => x.CoinId == item.CoinId);
                    coin.Quantity += 1;
                    _context.Update(coin);
                    await _context.SaveChangesAsync();
                }
            }

            return RedirectToAction(nameof(Index));
        }
        // Return Json data to view
        public JsonResult GraphicData()
        {
            return Json(_context.CoinContexts.Select(x => new { x.Name, x.Quantity }));
        }

        // GET: Coins/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coin = await _context.CoinContexts
                .FirstOrDefaultAsync(m => m.CoinId == id);
            if (coin == null)
            {
                return NotFound();
            }

            return View(coin);
        }

        // GET: Coins/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Coins/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CoinId,Name,Quantity")] Coin coin)
        {
            if (ModelState.IsValid)
            {
                coin.Quantity = 0; // Initial value 0
                _context.Add(coin);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coin);
        }

        // GET: Coins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coin = await _context.CoinContexts.FindAsync(id);
            if (coin == null)
            {
                return NotFound();
            }
            return View(coin);
        }

        // POST: Coins/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CoinId,Name,Quantity")] Coin coin)
        {
            if (id != coin.CoinId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(coin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CoinExists(coin.CoinId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(coin);
        }

        // GET: Coins/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coin = await _context.CoinContexts
                .FirstOrDefaultAsync(m => m.CoinId == id);
            if (coin == null)
            {
                return NotFound();
            }

            return View(coin);
        }

        // POST: Coins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var coin = await _context.CoinContexts.FindAsync(id);
            _context.CoinContexts.Remove(coin);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CoinExists(int id)
        {
            return _context.CoinContexts.Any(e => e.CoinId == id);
        }
    }
}

CryptoCoins/ViewComponents/CoinViewComponent.cs
using CryptoCoins.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CryptoCoins.ViewComponents
{
    public class CoinViewComponent : ViewComponent
    {
        private readonly CoinContext _coinsContext;

        // Dependency injection
        public CoinViewComponent(CoinContext coinsContext) 
        {
            _coinsContext = coinsContext;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _coinsContext.CoinContexts.ToListAsync());
        }
    }
}

CryptoCoins/Views/Coins/Create.cshtml
@model CryptoCoins.Models.Coin

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Coin</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CryptoCoins/Views/Coins/Delete.cshtml
@model CryptoCoins.Models.Coin

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Coin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CoinId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CryptoCoins/Views/Coins/Details.cshtml
@model CryptoCoins.Models.Coin

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Coin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CoinId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CryptoCoins/Views/Coins/Edit.cshtml
@model CryptoCoins.Models.Coin

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Coin</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CoinId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CryptoCoins/Views/Coins/Index.cshtml
@model IEnumerable<CryptoCoins.Models.Coin>

@{
    ViewData["Title"] = "Index";
}

<h2></h2>

<p>
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</p>
@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CoinId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CoinId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CoinId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>*@

<div class="row">
    <div class="well col-lg-6">
        @await Component.InvokeAsync("Coin")
    </div>
    <div class="col-lg-6">
        <partial name="_Graphic" />
    </div>
</div>

<script>
    function GetCoins(data) {
        let quantity = 0;
        let coins = [];

        while (quantity < data.length) {
            coins.push(data[quantity].name);
            quantity++;
        }

        return coins;
    }

    function GetQuantity(data) {
        let quantity = 0;
        let values = [];

        while (quantity < data.length) {
            values.push(data[quantity].quantity);
            quantity++;
        }

        return values;
    }

    function GetColors(quantity) {
        let colors = [];

        while (quantity >= 0) {
            let r = Math.floor(Math.random() * 255);
            let g = Math.floor(Math.random() * 255);
            let b = Math.floor(Math.random() * 255);

            colors.push("rgb(" + r + "," + g + "," + b + ")");

            quantity--;
        }

        return colors;
    }

    $.ajax({
        type: 'GET',
        url: 'Coins/GraphicData',
        success: function (data) {
            new Chart(document.getElementById('graphic'), {
                type: 'pie',
                data: {
                    labels: GetCoins(data),
                    datasets: [{
                        labels: 'Quantity',
                        borderWidth: 2,
                        backgroundColor: GetColors(data.length),
                        data: GetQuantity(data)
                    }]
                },
                options: {
                    title: {
                        display: true,
                        text: 'Coins quantity'
                    }
                }
            });
        }
    });
</script>

CryptoCoins/Views/Coins/_Graphic.cshtml
<canvas id="graphic">
    
</canvas>

CryptoCoins/Views/Shared/Components/Coin/Default.cshtml
@model IList<CryptoCoins.Models.Coin>

<h4>Which crypto coin do you buy?</h4>
<hr />

<form asp-controller="Coins" asp-action="CryptoChoice" method="post" class="form-group">
    @for (int i = 0; i < Model.Count; i++)
    {
        <input type="checkbox" asp-for="@Model[i].IsChecked" />
        <label asp-for="@Model[i].IsChecked">@Model[i].Name</label>

        <input asp-for="@Model[i].CoinId" type="hidden" />
        <input asp-for="@Model[i].Name" type="hidden" />

        <br />
    }

    <input type="submit" value="Submit" class="btn btn-default"/>
</form>

CryptoCoins/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CryptoCoins</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="~/lib/jquery/dist/jquery.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Coins" asp-action="Index" class="navbar-brand">CryptoCoins</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li><a asp-area="" asp-controller="Coins" asp-action="Index">Home</a></li>*@
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; 2021 - CryptoCoins by Lucas Santana</p>
        </footer>
    </div>

    <environment include="Development">
        
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/Chart.js/Chart.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/Chart.js/Chart.bundle.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>